### ISSUE TITLE
Add more arguments to publish_as_nanopub method

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#105]
The `Nanopub.from_assertion` method that the `publish_as_nanopub` method is based on accepts arguments `attributed_to`, `attribute_to_profile`, and `nanopub_author`. We should allow the user to pass those arguments also to `publish_as_nanopub` so when publishing a workflow or step users can control the author of the nanopub and the assertion.

**Comment by raar1** [comment]
Yes, exactly - in fact, I was about to create this issue myself!

There are some points to consider first - in principle many useful triples may be desirable in the ```provenance``` subgraph. Some of these, like ```wasDerivedFrom``` are so common they could well belong as kwargs in their own right, but there should maybe be a way to add other triples to the provenance graph at this stage?

One possibility is to simply have ```**kwargs``` in the function signature, and check the keys of that dict for any that match a given list of predicates from the ```http://www.w3.org/ns/prov#``` ontology. That would give users the ability to add any of those properties quickly, without our code ballooning up.

We have a similar issue with ```pubinfo```, potentially, but I'm not sure that is such a common one that it necessarily needs to be in ```from_assertion```.

**Comment by raar1** [comment]
Actually, most of the above is better seen as a ```nanopub``` issue - I'll move it there.

**Comment by svenvanderburg** [comment]
Indeed, that is more a nanopub issue! This is about fairworkflows where we currently don't have any control over the provenance, and addding what we already have currently in nanopub (`attributed_to`, `attribute_to_profile`, and `nanopub_author`) is already a huge step. We could implement this with a `kwargs` argument that is to be passed to the from_assertion method of Nanopub.

**Comment by svenvanderburg** [comment]
This is blocked by: https://github.com/fair-workflows/nanopub/issues/39

**Comment by svenvanderburg** [comment]
See [resulting nanopublicaiton](http://test-server.nanopubs.lod.labs.vu.nl/RA7qXleC_p0dLcxesjQWJCVJLh3PcnHQtsS-5dTjQsi0A)
