### ISSUE TITLE
Allow control over which steps to publish for FairWorkflow.publish_to_nanopub()

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#106]
It has been raised in previous discussions that some users may not want to publish all steps (FAIR doesn't mean open, etc etc). In such a case a user may wish to control which they do and don't publish.

**Comment by svenvanderburg** [comment]
Some options for allowing more control:
- A publish_all_steps kwarg for FairWorkflow.publish_to_nanopub() that is True by default. But how to control which steps to publish?
- A property of Fairstep: `allow_publish`, that toggles publishing it when we publish the workflow. By default it is True. I vote for this.

**Comment by svenvanderburg** [comment]
We need some way of referencing the step without it being published.

Some options:
- A blank node with a 'unique' name (so that it gets tranformed by nanopub into PUBLISHED_NANOPUB_URI#blanknodename as usual).

@tkuhn what do you suggest?

**Comment by tkuhn** [comment]
Can't you do that already now? You can represent a step in a nanopub and make it trusty. Then you have a URI for that nanopub and for the step, which you can refer to in another nanopub. And then you can publish the latter nanopub without publishing the former.

**Comment by raar1** [comment]
Ah I see, the trustyfication produces an essentially unique URI (I guess collisions would be very rare...) so you already know what the published URI would be, regardless of whether it is published or not. Good point, we can just trustify everything locally as standard.

**Comment by raar1** [comment]
So from now on we can store all steps and workflows locally in their trustified form, and publish all of them (or a desired subset) if chosen by the user. The question now would be: do we create these (local) trusty nanopubs continuously - as in, every time something is changed, do we write a new trustified nanopub to disk? Sounds onerous, and could be tricky to update all the URIs elsewhere every time.

I think instead that we just keep all this happening in the ```publish_to_nanopub()```, and maybe add some flags like ```keep_local``` or something. A danger we should look out for is if a user were to add a step to the workflow, and then publish that step using the original step object - does the workflow update its URI of that step? I think we deep copy steps anyway, so technically the one pointed to by the workflow object is a "different" step. But does the user know/expect that?

**Comment by tkuhn** [comment]
Yes. Collitions are theoretically possible but practically not. I am using SHA-256 which is expected to remain a save hashing function for the foreseeable future, so there have been *zero* collisions so far.

There could be on the user interface side something similar to "commit" and "commit & push" with git. The latter could be default.

I am not sure I understand your last point. You can add `npx:supersedes` relations in the pubinfo part pointing to the previous version, and then you can use the `get_latest_version` API call to get the latest version(s), assuming they are signed with the same key.

**Comment by raar1** [comment]
Thanks @tkuhn . Don't worry about the last point, it was more regarding the internals of the library itself (robustness of updating references throughout the rdf graph, and making sure stale python objects are not mistaken for the same step) rather than a problem with multiple nanopubs being created. But that would indeed be a good idea to use ```npx:supercedes``` for any local nanopubs anyway to keep everything clear/consistent.

**Comment by svenvanderburg** [comment]
We could use the trusty unpublished URI, problem is that there will be broken links in the published workflow. And no way at all to let user know that it is intentionally not published.

**Comment by svenvanderburg** [comment]
## Possible solution:
* Publish workflow with trusty unpublished URI that will thus be broken
* Add a triple stating that at time of publihsing this step was not published (yet)

Downside:
* There is no single source that says something about this broken link

## An already possible workaround:
* If you don't want to publish a step but refer to it in a workflow you can just publish a step that does not have the full step description but just some triples with meta information and that it is not a full description.

Closing issue because there is no immediate urge for this functionality and we don't have a very intuitive way of doing this apart from the already possible workaround above.
