### ISSUE TITLE
Allow user to specify that a FairStep was derived_from something

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#116]
If a FairStep is created from scratch, it is assumed the code did not originate from something else (such as a nanopub) but it may have. We should have a way to specify a URI that the step was (somehow) derived from.

**Comment by svenvanderburg** [comment]
* [ ] Add `derived_from` property for `RdfWrapper` with getter and setter.
* [ ] When you fetch a `RdfWrapper` object from nanopub we should set the `derived_from` property to the same value as the fetched nanopub object.
