### ISSUE TITLE
execute option for a workflow and a step

### ISSUE THREAD

**Issue by rcelebi** [fair-workflows/fairworkflows#119]
After describing a workflow or a step, we should be able to execute it. For example:

@add_step(workflow)
def resize_image(image:Image) -> Image:    
    """Resize the image 300x300 """
    new_image = image.resize((300, 300))
    return new_image

im1 = Image.open('images/demo_image.jpg')

im2 = resize_image.execute(im1)
im2 = workflow.execute(im1)

**Comment by raar1** [comment]
This is now being handled in #136, #141 etc
