### ISSUE TITLE
Steps without URI are reffered to as <None> in workflow RDF.

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#130]
```python
step1 = FairStep()
workflow = FairWorkflow()
workflow.add(step1)
print(workflow)
```
prints:
```
Workflow URI = None
@prefix pplan: <http://purl.org/net/p-plan#> .
@prefix pwo: <http://purl.org/spar/pwo/> .

_:Nc4cbc97adddf4b6396c0ff18497b6fae {
    <None> pplan:isStepOfPlan [ a pplan:Plan ;
                pwo:hasFirstStep <None> ] .
}
```
As you can see we refer to the step as <None> which does not make any sense. This is because we try to use the uri of the `FairStep` object to refer to it and this is None. 
When trying to publish this we get:
```
RuntimeError: Error in nanopub java application: org.eclipse.rdf4j.rio.RDFParseException: Not a valid (absolute) IRI: /None [line 19]
```
We should make use of the FairStep.self_ref. That likely breaks the code in different places though.

Requirements:
* [ ] Fix reference from workflows to steps that don't have a URI
* [ ] Fix publication of workflows with steps that don't have a URI

**Comment by raar1** [comment]
Fixed in #154
