### ISSUE TITLE
Provide display() with reduced information density

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#142]
Currently we convert RDF to ```dot```, which provides a lot of information that can be too cluttered for a user who wants to understand only the computational flow. We should provide an option to display a simpler graph. Easiest would be to adapt get_workflow_graph() from the noodles tutorial.

**Comment by raar1** [comment]
The ```display()``` method of ```FairWorkflow``` now distinguishes between ```full_rdf=True``` which uses the ```rdf2dot``` functionality, and a default of ```full_rdf=False``` which (currently) uses the noodles workflow display from the tutorial. We should find a nicer way to reconcile/combine these two different display approaches.

**Comment by svenvanderburg** [comment]
- [ ] `display()` should only show function name of the step and the label, and connections to other steps
- [ ] `display_as_rdf()` should display the full rdf
- [ ] `display_as_rdf()` should also become available for FairStep (so maybe implement at `RdfWrapper` level)

**Comment by svenvanderburg** [comment]
Fixed by #178
