### ISSUE TITLE
When publishing a workflow, raise error if not all steps are published yet

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#152]
When publishing a workflow, raise an error if not all steps are published yet. We want the user to manually publish those steps as separate nanopublications.
* Raise error if not all steps are published yet
* Remove all code that publishes a workflow *including* the steps in the RDF
* Remove all code that creates a workflow and steps from workflow RDF that includes triples describing steps.

**Comment by raar1** [comment]
This has been addressed in PR #153
