### ISSUE TITLE
FairStep and FairWorkflow objets should deserialize trig/ttl files passed to them

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#72]
A user should be able to provide an rdf file (in general formats such as turtle, trig etc) and the fairworkflows library will deserialize it, producing the appropriate FairStep and FairWorkflow objects from it, allowing validation under the chosen ontology.

**Comment by svenvanderburg** [comment]
@raar1 wouldn't it make more sense if users just use rdflib to deserialize their RDF files? And then just construct a FairStep or FairWorkFlow based on the resulting RDF Graph object. This is actually already the case for FairStep (and https://github.com/fair-workflows/FAIRWorkbench/pull/75 makes it even more explicit).

We could add an example of deserializing a (for example turtle) file in the documentation later. (or in the readme for now)

**Comment by raar1** [comment]
@svenvanderburg that does indeed sound like a very sensible solution!
