### ISSUE TITLE
Change wasDerivedFrom in Nanopub module to point to the assertion graph

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#77]
At present nanopubs describing ```FairStep```s that were derived from other nanopubs use ```prov:wasDerivedFrom``` with the original nanopublication URI as object. Conceptually it is preferable that the given URI be that of the assertion graph of the original nanopub (i.e. with fragment ```#assertion```).

This minor change can wait until PRs #75 and #76 are merged.

**Comment by raar1** [comment]
A problem with this is that nanopubs are sometimes derived from URIs which do not point to other nanopubs. So using the assertion subgraph URI requires the library to know whether the source URI is a nanopub.

**Comment by svenvanderburg** [comment]
This is obsolete! See https://github.com/fair-workflows/fairworkflows/blob/aa0c56ec94e7b711b000d98484657b4d6b509dd4/fairworkflows/rdf_wrapper.py#L153
