### ISSUE TITLE
Apply PLEX SHACL validation, and move towards conformity

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#85]
We now have a SHACL file (generated by Remzi) for the PLEX ontology. It can be found at [https://github.com/fair-workflows/fairworkflows/blob/master/shacl/plex-shapes.ttl](https://github.com/fair-workflows/fairworkflows/blob/master/shacl/plex-shapes.ttl).

We need to use this to check where we are currently not conforming to the ontology (I suspect there are a number of areas), and eventually work it into the fairworkflows validation itself.

**Comment by raar1** [comment]
See the following for an example of trig that should validate with this SHACL: 
[https://github.com/fair-workflows/FAIR-WFcollection/blob/master/ml-classify-text/rdf/ml-classify-text.ttl](https://github.com/fair-workflows/FAIR-WFcollection/blob/master/ml-classify-text/rdf/ml-classify-text.ttl)

**Comment by svenvanderburg** [comment]
Fixed by https://github.com/fair-workflows/fairworkflows/pull/87
