### ISSUE TITLE
Only copy relevant RDF statements

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/fairworkflows#96]
Only copy relevant RDF statments when constructing FairWorkflow and FairStep objects from RDF. We now copy all statements.

See https://github.com/fair-workflows/fairworkflows/blob/0e56681eec3b73317115f51b86349b1763f91072/fairworkflows/fairstep.py#L47

and https://github.com/fair-workflows/fairworkflows/blob/0e56681eec3b73317115f51b86349b1763f91072/fairworkflows/fairworkflow.py#L63

**Comment by svenvanderburg** [comment]
Solving this in: #99

**Comment by raar1** [comment]
Fixed by PR #99
